import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const myClass = "bg-slate-100 dark:bg-slate-900 dark:text-white " + inter.className

  return (
    <html lang="en">
      <body className={myClass}>{children}</body>
    </html>
  )
}
